FROM python:3.7

ENV FLASK_APP integrator_app.py
ENV FLASK_CONFIG test
ENV ENV_FILE .env_test

WORKDIR /home/integrator_proj

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY integrator integrator
COPY migrations migrations
COPY integrator_app.py config.py start_app.sh '.env_test' ./

RUN chmod +x ./start_app.sh

EXPOSE 5000