version: '3'
services:
  redis:
    image: 'redis'
    container_name: integrator_redis
    ports:
    - '6379:6379'

  webapp:
    build: .
    container_name: integrator_main
    ports:
    - "5000:5000"
    volumes:
    - ./data.sqlite:/home/integrator_proj/data.sqlite
    command: "gunicorn --bind :5000 integrator_app:app"
    links:
    - redis
    depends_on:
    - redis

  celery:
    build: .
    container_name: integrator_celery
    volumes:
    - ./data.sqlite:/home/integrator_proj/data.sqlite
    command: "celery -A integrator_app.celery worker --concurrency=1"
    links:
    - redis
    depends_on:
    - redis

  sceduler:
    build: .
    container_name: integrator_sceduler
    volumes:
    - ./data.sqlite:/home/integrator_proj/data.sqlite
    command: "celery -A integrator_app.celery beat --loglevel=INFO"
    links:
    - redis
    depends_on:
    - redis
    - celery