version: '3'
services:
  redis:
    image: 'redis'
    container_name: integrator_redis
    restart: always
    ports:
    - '6379:6379'
    networks:
    - integrator

  integrator_app:
    build: .
    container_name: integrator_main
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - ./data.sqlite:/home/integrator_proj/data.sqlite
    command: "./start_app.sh"
    networks:
    - integrator
    depends_on:
    - redis

#  postgresql:
#    restart: always
#    image: 'postgres:11'
#    container_name: integrator_postgres
#    ports:
#    - "5432:5432"
#    env_file:
#      .env-postgres
#    volumes:
#    - integrator_volume:/var/lib/postgresql/data
#    networks:
#    - integrator

#  pgbackups:
#    image: prodrigestivill/postgres-backup-local
#    restart: always
#    volumes:
#      - /var/opt/pgbackups:./backups
#    network:
#      - integrator
#    depends_on:
#      - postgresql
#    env_file:
#      .env-postgres-test
#    environment:
#      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
#      - SCHEDULE=@daily
#      - BACKUP_KEEP_DAYS=7
#      - BACKUP_KEEP_WEEKS=4
#      - BACKUP_KEEP_MONTHS=6
#      - HEALTHCHECK_PORT=80

  nginx:
    restart: always
    build: ./nginx
    networks:
    - integrator
    expose:
    - 8080
    ports:
    - "8080:8080"
    depends_on:
    - integrator_app

networks:
  integrator:
    driver: bridge

#  celery:
#    build: .
#    container_name: integrator_celery
#    volumes:
#    - ./data.sqlite:/home/integrator_proj/data.sqlite
#    command: "celery -A integrator_app.celery worker --concurrency=1"
#    networks:
#    - integrator
#    depends_on:
#    - redis
#
#  sceduler:
#    build: .
#    container_name: integrator_sceduler
#    volumes:
#    - ./data.sqlite:/home/integrator_proj/data.sqlite
#    command: "celery -A integrator_app.celery beat --loglevel=INFO"
#    networks:
#    - integrator
#    depends_on:
#    - redis
#    - celery
